### ISSUE TITLE
Enahce Cluster metadata algorithm

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-cluster#117]
Run code snippet:
```java
    Cluster cluster0 = Cluster.joinAwait();
    Cluster cluster1 = Cluster.joinAwait(cluster0.address());

    cluster1
        .listenMembership()
        .filter(MembershipEvent::isUpdated)
        .subscribe(
            event -> {
              Map<String, String> metadata = cluster1.metadata(event.member());
              System.out.println(
                  "### metadata: "
                      + metadata
                      + " | "
                      + System.currentTimeMillis()
                      + " | "
                      + Thread.currentThread().getName());
            });

    cluster0.updateMetadataProperty("key", "value1").subscribe(); // 1
    cluster0.updateMetadataProperty("key", "value2").subscribe(); // 2
    cluster0.updateMetadataProperty("key", "value3").subscribe(); // 3

    Thread.currentThread().join();
```

May give following:
```
### metadata: {key=value3} | 1544874450633 | sc-cluster-44033-2
### metadata: {key=value3} | 1544874450634 | sc-cluster-44033-2
### metadata: {key=value3} | 1544874450641 | sc-cluster-44033-2
```

Which tells us following:
Cluster metadata algorithm did three rpc calls and opon each call he received the latest metdata value. Why latest? Because update on cluster0  occurs immediately, while incarnation-update travelling by network. That's why locally at cluster0 I get value3 but 3 incarnation updates  in flyight to other nodes.

What's not great -- extra network calls to get metadata. Propose a solution.

**Comment by snripa** [comment]
Here the guess was almost correct, with small correction. All gossips spread very fast, all gossips about update come to the remote node sooner that the node 2 completes the first call to fetch metadata.

**Comment by snripa** [comment]
The attempt to avoid the extra calls that is based on incarnationsis as follows: inside metadata we store it's version(incarnation). Any time we receive gossib that notifies about member update - we compare membershipEvent's incarnation to the incarnation for which we have stored metadata. 

Make call to fetch metadata if only incarnation in membershipEvent is higher that the one in metadata.

**Comment by snripa** [comment]
'
D 0008:59,103 i.s.c.m.MetadataStoreImpl Updated metadata: {key=0, incarnation=1} for local member (DBB8D662C779BF44A865@127.0.0.1:55103) [sc-cluster-55103-1]
D 0008:59,104 i.s.c.m.MetadataStoreImpl Updated metadata: {key=1, incarnation=2} for local member (DBB8D662C779BF44A865@127.0.0.1:55103) [sc-cluster-55103-1]
D 0008:59,104 i.s.c.m.MetadataStoreImpl Updated metadata: {key=2, incarnation=3} for local member (DBB8D662C779BF44A865@127.0.0.1:55103) [sc-cluster-55103-1]
D 0008:59,105 i.s.c.m.MetadataStoreImpl Updated metadata: {key=3, incarnation=4} for local member (DBB8D662C779BF44A865@127.0.0.1:55103) [sc-cluster-55103-1]
D 0008:59,105 i.s.c.m.MetadataStoreImpl Updated metadata: {key=4, incarnation=5} for local member (DBB8D662C779BF44A865@127.0.0.1:55103) [sc-cluster-55103-1]
I 0008:59,162 i.s.c.m.MembershipProtocolImpl Member updated: DBB8D662C779BF44A865@127.0.0.1:55103(1). Currently stored metadata for it: 0 [sc-cluster-55104-2]
D 0008:59,163 i.s.c.m.MetadataStoreImpl Getting metadata for member DBB8D662C779BF44A865@127.0.0.1:55103 [sc-cluster-55104-2]
I 0008:59,163 i.s.c.m.MembershipProtocolImpl Member updated: DBB8D662C779BF44A865@127.0.0.1:55103(2). Currently stored metadata for it: 0 [sc-cluster-55104-2]
D 0008:59,164 i.s.c.m.MetadataStoreImpl Getting metadata for member DBB8D662C779BF44A865@127.0.0.1:55103 [sc-cluster-55104-2]
I 0008:59,164 i.s.c.m.MembershipProtocolImpl Member updated: DBB8D662C779BF44A865@127.0.0.1:55103(3). Currently stored metadata for it: 0 [sc-cluster-55104-2]
D 0008:59,165 i.s.c.m.MetadataStoreImpl Getting metadata for member DBB8D662C779BF44A865@127.0.0.1:55103 [sc-cluster-55104-2]
D 0008:59,165 i.s.c.m.MetadataStoreImpl Received GetMetadataReq: Message {headers: {q=sc/metadata/req, cid=C6514245D4E030BECEC1-2}, sender: 127.0.0.1:55104, data: GetMetadataRequest{member=DBB8D662C779BF44A865@127.0.0.1:55103}} [sc-cluster-55103-1]
D 0008:59,165 i.s.c.m.MetadataStoreImpl Send GetMetadataResp: Message {headers: {q=sc/metadata/resp, cid=C6514245D4E030BECEC1-2}, sender: 127.0.0.1:55103, data: GetMetadataResponse{member=DBB8D662C779BF44A865@127.0.0.1:55103, metadata={key=4, incarnation=5}}} to 127.0.0.1:55104 [sc-cluster-55103-1]
I 0008:59,165 i.s.c.m.MembershipProtocolImpl Member updated: DBB8D662C779BF44A865@127.0.0.1:55103(4). Currently stored metadata for it: 0 [sc-cluster-55104-2]
D 0008:59,165 i.s.c.m.MetadataStoreImpl Getting metadata for member DBB8D662C779BF44A865@127.0.0.1:55103 [sc-cluster-55104-2]
I 0008:59,166 i.s.c.m.MembershipProtocolImpl Member updated: DBB8D662C779BF44A865@127.0.0.1:55103(5). Currently stored metadata for it: 0 [sc-cluster-55104-2]
D 0008:59,166 i.s.c.m.MetadataStoreImpl Getting metadata for member DBB8D662C779BF44A865@127.0.0.1:55103 [sc-cluster-55104-2]
D 0008:59,167 i.s.c.m.MetadataStoreImpl Received GetMetadataReq: Message {headers: {q=sc/metadata/req, cid=C6514245D4E030BECEC1-3}, sender: 127.0.0.1:55104, data: GetMetadataRequest{member=DBB8D662C779BF44A865@127.0.0.1:55103}} [sc-cluster-55103-1]
D 0008:59,168 i.s.c.m.MetadataStoreImpl Send GetMetadataResp: Message {headers: {q=sc/metadata/resp, cid=C6514245D4E030BECEC1-3}, sender: 127.0.0.1:55103, data: GetMetadataResponse{member=DBB8D662C779BF44A865@127.0.0.1:55103, metadata={key=4, incarnation=5}}} to 127.0.0.1:55104 [sc-cluster-55103-1]
D 0008:59,171 i.s.c.m.MetadataStoreImpl Received GetMetadataReq: Message {headers: {q=sc/metadata/req, cid=C6514245D4E030BECEC1-4}, sender: 127.0.0.1:55104, data: GetMetadataRequest{member=DBB8D662C779BF44A865@127.0.0.1:55103}} [sc-cluster-55103-1]
D 0008:59,171 i.s.c.m.MetadataStoreImpl Send GetMetadataResp: Message {headers: {q=sc/metadata/resp, cid=C6514245D4E030BECEC1-4}, sender: 127.0.0.1:55103, data: GetMetadataResponse{member=DBB8D662C779BF44A865@127.0.0.1:55103, metadata={key=4, incarnation=5}}} to 127.0.0.1:55104 [sc-cluster-55103-1]
'

**Comment by artem-v** [comment]
Agreed to close. Thanks for such deep investigation @snripa  !
