### ISSUE TITLE
Failure Detector Configurator

### ISSUE THREAD

**Issue by antonkharenko** [scalecube/scalecube-cluster#134]
Implement Failure Detector Configurator component. Failure Detector Configurator is responsible to compute specific FD algorithm parameters based on the required QoS and given network reliability parameters.

Input: 
- Parameters of failure detector quality of service (QoS) requirements. QoS parameters should be set by configuration.
- Network reliability parameters. Network Reliability Parameters should be (for now) statically configured with some typical values.

Output: 

Computed configuration parameters of used Failure Detector Algorithm (Tping, K) based on input parameters.

More on the math for used FD algorithm can be found at paper ["On Scalable and Efficient Distributed Failure Detectors"](http://www.cs.cornell.edu/projects/quicksilver/public_pdfs/On%20Scalable.pdf) and general information  regards QoS parameters of FD at ["On the Quality of Service of Failure Detectors"](http://research.microsoft.com/en-us/people/weic/ieeetc02_fdqos.pdf).

**Comment by ronenhamias** [comment]
closing it until one day it show up again.
closing it as lack of public interest.
