### ISSUE TITLE
Migrate to RSocket and Remove Scalecube Transport 

### ISSUE THREAD

**Issue by ronenhamias** [scalecube/scalecube-cluster#165]
Motivation:

the idea is to completely refactor and delete [scalecube-transport](https://github.com/scalecube/scalecube-cluster/tree/develop/transport) that is now days only used by [scalecube-cluster.](https://github.com/scalecube/scalecube-cluster/)

once we complete this migration and use pluggable RSocket (Netty or Aeron) 
Cluster may use RSocket-Aeron as its transport layer and as result remove current custom transport layer.

The Value:

1. you want better communication modes then send and receive provided by scalecube self invented transport. 
2. you want to enjoy all the power of scalecube-cluster and swim and gossip features plus tags ect.
3. we want to use widely adopted standards or a standard then self invented ones.

if the answer is yes for the points above then ScaleCube-cluster is the right answer for you. :)

Design considerations:
1. remove the transport module completely. we will no longer have transport at all and RSocket will be our abstraction.
2. make rsocket  pluggable to cluster  so we can choose  aeron or netty or any rsocket implementation - user will bring his own RSocket(Factory?).

**Comment by ronenhamias** [comment]
> I think it will be great because we won't need to support integration with `reactor-netty` in the future (I heard that they plan to refactor a lot)

its a good value to use RSocket

**Comment by bsideup** [comment]
@ronenhamias 
> several impl of RSocket

I would say - make it a part of the cluster's builder, and let the user "bring his own RSocket(Factory?)".
Currently it has `.transport()` sub-builder, something similar

**Comment by ronenhamias** [comment]
@bsideup @dmytro-lazebnyi @segabriel 

i have updated the requirements and vision for this change according to your valuable inputs thank you all!

please review and if you have more comment or ideas please do share

**Comment by ronenhamias** [comment]
rsocket seem not to fit in this case
