### ISSUE TITLE
Refactor NetworkEmulator find alternative

### ISSUE THREAD

**Issue by ronenhamias** [scalecube/scalecube-cluster#171]
Currently NetworkEmulator is embedded in the production code while this should be external tool.

remove it and find alternative solution

**Comment by artem-v** [comment]
@ronenhamias 
> is embedded in the production code
it's not
it's disabled by default, and activated explicitly 
Plus `NetworkEmulator` is already decoupled from Transpotr implementation.

**Comment by artem-v** [comment]
Agreed to have NetworkEmulator in the tests only. Don't have  it  as a dependency inside TrasnportImpl.
