### ISSUE TITLE
Gossip on AWS instances of different regions

### ISSUE THREAD

**Issue by swapnil-pandey** [scalecube/scalecube-cluster#173]
So I am using the scalecube-cluster for reasons of membership and gossip among different nodes hosted on **different** aws zones. The problem I am facing is that although I am able to join a cluster when I use `spreadGossip` other nodes do not receive anything. But the problem vanishes if I am using all the nodes of the same zone.

For example:
there are 3 nodes in us-west (N. California) and 1 in Sydney and 1 in Brazil.
The 3 USA nodes are able to send and receive messages through `spreadGossip` but the Sydney and brazil nodes are not taking part in the communication. And if I print the size of the cluster it says **4**. So although the nodes are in the cluster, they are not able to send/receive messages.

Can anyone shed some light on this? Are there any specific ports that need to be opened on the aws instances. ( I am running the cluster through `ClusterConfig clientConfigWithFixedPort` with the port as 3000).

**Comment by glcheng** [comment]
Hi, I'm also using this on AWS, and experience no problems between regions. I guess your problem is related to the security group settings?
