### ISSUE TITLE
Dead members in GossipProtocolImpl class

### ISSUE THREAD

**Issue by glcheng** [scalecube/scalecube-cluster#176]
Version 1.X has a bug where dead members are not removed from the GossipProtocolmpl class, because the 'backpressuredrop' is used, which causes some events to be dropped. What you see in the logs are connect errors to the dead hosts. These errors will never go away, and will always appear when the class is trying to gossip to these dead hosts.

**Comment by artem-v** [comment]
Version 1.X was decomissioned some time ago (as my mind last year). We are not longer maintain it or have plans to maintain.

**Comment by artem-v** [comment]
Can you please verify that this no longer happens in current latest release 2.2.4.

**Comment by glcheng** [comment]
I'm not running any 2.X version, because I waiting for 2.2.5. But looking
at the code, it should not happen anymore in 2.X.

Gin

**Comment by artem-v** [comment]
Thanks
You know what, we will make 2.2.5 for you

**Comment by glcheng** [comment]
Haha, ok thanks :P

**Comment by artem-v** [comment]
@glcheng 
https://github.com/scalecube/scalecube-cluster/pull/179
wait for ~1hr
