### ISSUE TITLE
Unstable test (FailureDetectorTest#testStatusChangeAfterMemberRestart)

### ISSUE THREAD

**Issue by segabriel** [scalecube/scalecube-cluster#186]
Target is `io.scalecube.cluster.fdetector.FailureDetectorTest#testStatusChangeAfterMemberRestart`
It's bthaved unstable in `develop` branch as well. If fire-up only this test it's failed. Also it's failed persistently with new version of reactor.
see also  #185

**Comment by ronenhamias** [comment]
fixed
