### ISSUE TITLE
gossip does not work when the messages are objects

### ISSUE THREAD

**Issue by devas123** [scalecube/scalecube-cluster#201]
Hi!
When i try to gossip a message that is not a string, the members do not receive it, and there are no errors in the log.

I have attached a minimal example
[test.zip](https://github.com/scalecube/scalecube-cluster/files/3233256/test.zip)

**Comment by artem-v** [comment]
@devas123 
Yes, indeed,  look into this

**Comment by artem-v** [comment]
@devas123 
In your class `Msg` , remove qualifier `final` at field `payload`  and create default constructor for class.

**Comment by artem-v** [comment]
Likely you are getting ```com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `test.Msg` (although at least one Creator exists): cannot deserialize from Object value (no delegate- or property-based Creator)```

**Comment by devas123** [comment]
ah... ok. with the default constructor it works. Thank you!
