### ISSUE TITLE
Add cluster member name/alias (in addition to id)

### ISSUE THREAD

**Issue by dmytro-lazebnyi** [scalecube/scalecube-cluster#252]
It is hard to understand what is the exact member described by `id + "@" + address`, where `id` - is randomly generated value.

@artem-v @segabriel

**Comment by segabriel** [comment]
`alias@id@address` :+1:

**Comment by artem-v** [comment]
Re-opening. 
The way how this was done at https://github.com/scalecube/scalecube-cluster/releases/tag/v2.4.3 is not correct.
