### ISSUE TITLE
Make cluster metadata as key/value bytes rather then strings

### ISSUE THREAD

**Issue by ronenhamias** [scalecube/scalecube-cluster#30]
Today cluster metadata is limited to string and this forces the use of json for example when using discovery.

changing to byte array key value will give more flexibility applying different objects and formats

**Comment by artem-v** [comment]
Something good to start with:

1) Codec interface:
```
MetadataCodec<T> {
  T deserialize(InputStream is) throws Exception;
  void serialize(T metadata, OutputStream os) throws Exception;
}
```
2) `MetadataStoreImpl`  must come configurable with client provided (as well as default one) metadata codec instance.

**Comment by artem-v** [comment]
After digesting this issue important update has emerged: 

1. Metadata must be finite chunk of bytes (byte[] or j.n.ByteBuffer, but **not** the netty's ByteBuf) and must lying in MetadataStore (just like as it's now). It can be stored in-heap or off-heap, doesn't matter at this point. 

2. Upon `MetadataCodec` (MC) mentioned in prev. comment: 
- MC must be passed by the client code when he will be calling for concrete metadata; i.e. MC must be applied on demand;  I.e.  end-client functions with metadata must be changed: 
- `Map<String, String> Cluster.metadata()` -> `T Cluster.metadata(Class<T>, MC)` 
_// Returns local cluster member metadata_
- `Map<String, String> Cluster.metadata(Member)` -> `T Cluster.metadata(Member, Class<T>, MC)` 
_// Returns cluster member metadata by given member reference_
- `Cluster.updateMetadata(Map<String, String>)` -> `Cluster.updateMetadata(T, MC)` 
_// Updates local member metadata with the given metadata map (no! object type T)_

3. Functions `Cluster.updateMetadataProperty` and `Cluster.removeMetadataProperty`  must be removed.

**Comment by segabriel** [comment]
What about `MetadataStore`? What methods should it have?
