### ISSUE TITLE
Compatible with Reactor Netty 1.0.0 

### ISSUE THREAD

**Issue by linux-china** [scalecube/scalecube-cluster#351]
Reactor Netty 1.0.0 has been released  https://github.com/reactor/reactor-netty/releases/tag/v1.0.0    Lots of APIs changed, and should be compatible with Reactor Netty 1.0.0

**Comment by linux-china** [comment]
any news?    :)   Reactor Netty 1.0 has io_uring support already, and this feature is very important for server side.   Scalecube-cluster manages the lots of nodes in the cluster,  and it will be great for performance if Scalecube cluster supports Reactor Netty 1.0 .

**Comment by artem-v** [comment]
Try this one https://github.com/scalecube/scalecube-cluster/releases/tag/2.6.7.RC1.
